name: genrate artifacts

env:
  MSVC_TOOLSET: v143
  GXX_VERSION: 11

on:
  push:
    branches: [main]

jobs:
  token_check:
    if: "startsWith(github.event.head_commit.message, 'update:')"
    runs-on: ubuntu-latest
    steps:
    - run: echo "update token found."

  linux:
    needs: token_check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_mode: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - name: export tag
      run: |
        string="${{ github.event.head_commit.message }}"
        string="TAG_NAME=${string/update:/}"
        echo "$string" >> $GITHUB_ENV
    - name: Install compiler
      run: |
        sudo apt-get update
        sudo apt-get install g++-${{ env.GXX_VERSION }} -y
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ env.GXX_VERSION }} ${{ env.GXX_VERSION }}00 --slave /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GXX_VERSION }}
    - name: compile godot-cpp
      env:
        CC: gcc
        CXX: g++
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -Dgodot-cpp_pre-built_GODOT_CPP_TAG="${{ env.TAG_NAME }}" -B out -S .
        cmake --build out --target godot-cpp -j4
        cmake --build out -j4
    - name: compress artifacts
      run: zip -r linux-x64-${{ matrix.build_mode }}.zip godot-cpp
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64-${{ matrix.build_mode }}
        path: linux-x64-${{ matrix.build_mode }}.zip
        if-no-files-found: error

  windows:
    needs: token_check
    runs-on: windows-2022
    strategy:
      matrix:
        build_mode: [Debug]
    steps:
    - uses: actions/checkout@v3
    - name: export tag
      shell: bash
      run: |
        string="${{ github.event.head_commit.message }}"
        string="TAG_NAME=${string/update:/}"
        echo "$string" >> $GITHUB_ENV
    - name: compile godot-cpp
      run: |
        cmake -Dgodot-cpp_pre-built_GODOT_CPP_TAG="${{ env.TAG_NAME }}" -T"${{ env.MSVC_TOOLSET }}" -B out -S .
        cmake --build out --target godot-cpp -j4
        cmake --build out -j4
    - name: compress artifacts
      run: Compress-Archive -Path 'godot-cpp' -DestinationPath 'windows-x64-${{ matrix.build_mode }}.zip'
    - uses: actions/upload-artifact@v3
      with:
        name: windows-x64-${{ matrix.build_mode }}
        path: windows-x64-${{ matrix.build_mode }}.zip
        if-no-files-found: error

  publish:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: export tag
      run: |
        string="${{ github.event.head_commit.message }}"
        string="TAG_NAME=${string/update:/}"
        echo "$string" >> $GITHUB_ENV
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/linux-x64-Debug/linux-x64-Debug.zip,artifacts/linux-x64-Release/linux-x64-Release.zip,artifacts/windows-x64-Debug/windows-x64-Debug.zip"
        artifactErrorsFailBuild: true
        replacesArtifacts: true
        allowUpdates: true
        tag: v${{ env.TAG_NAME }}
